runtime: python37
instance_class: F4_1G
env_variables:
  GCP_PROJECT: "rsp-game-251717"
entrypoint: gunicorn -b :$PORT main:app

# The following parameters are optional
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301