runtime: python37
env_variables:
  GCP_PROJECT: "rsp-game"
entrypoint: gunicorn -b :$PORT main:app

# The following parameters are optional
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301